### ISSUE TITLE
model training

### ISSUE THREAD

**Issue by soniapolt** [cjnani16/deeprfs_tf#1]
get model training working with TF version 1.13

**Comment by cjnani16** [comment]
Main challenges here result from converting slightly functional tf2.0 to actual tf1.13 code. There are a couple broken pieces/places for improvement in the training process thus far:
- [ ] Fix checkpointing callback
- [ ] Make sample count during training work (Only train on a subset)
- [ ] Clean unnecessary model manipulations from cells
Luckily reaching reasonable accuracy ~80% seems to be a cinch thus far. But in order to use the full dataset (and after I succeed in achieving #3) I should try training on the full dataset with a larger BS on Nyla or some other more RAM-endowed computer.
